<?php require "../logic/display-users.php" ?>

<table class="col my-5 table table-striped">
    <thead>
    <tr>
        <th>
            #
        </th>
        <th>
            Nom d'utilisateur
        </th>
        <th>
            Email
        </th>
        <th>
            Mot de passe
        </th>
        <th>
            Rôle
        </th>
        <th>
            Supprimer
        </th>
    </tr>
    </thead>
    <tbody>
        <?php
        foreach($allUsers as $userData){
            
        echo
        "<tr>
            <td> - </td>
            <td> {$userData->getUsername()} </td>
            <td> {$userData->getEmail()} </td>
            <td> {$userData->getPassword()} </td>
            <td> {$userData->getRole()} </td>
            <td>
                <a href=\"../logic/delete-user.php?id=\" class=\"btn btn-danger\"><scan class=\"bi-trash-fill\"></scan></a>
            </td>
        </tr>";
        }?>
    </tbody>
    <tfoot>
    <tr>
        <th>
            #
        </th>
        <th>
            Nom d'utilisateur
        </th>
        <th>
            Email
        </th>
        <th>
            Mot de passe
        </th>
        <th>
            Rôle
        </th>
        <th>
            Supprimer
        </th>
    </tr>
    </tfoot>
</table>