<header>
    <nav>
        <ul>
            <li>
                <a href="https://maksymvoznichka.sites.3wa.io/PHP/J2/require/index.php?route=home">Accueil</a>
            </li>
            <li>
                <a href="https://maksymvoznichka.sites.3wa.io/PHP/J2/require/index.php?route=about">À propos</a>
            </li>
            <li>
                <a href="https://maksymvoznichka.sites.3wa.io/PHP/J2/require/index.php?route=contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>