<form action="logic/login.php" method="post">
    <fieldset class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email">
    </fieldset>
    <fieldset class="mb-3">
        <label for="password" class="form-label">Mot de passe</label>
        <input type="password" class="form-control" id="password" name="password">
    </fieldset>
    <button type="submit" class="btn btn-primary">Connexion</button>
</form>