<form action="logic/register.php" method="post">
    <fieldset class="mb-3">
        <label for="first_name" class="form-label">Prénom</label>
        <input type="text" class="form-control" id="first_name" name="first_name">
    </fieldset>
    <fieldset class="mb-3">
        <label for="last_name" class="form-label">Nom</label>
        <input type="text" class="form-control" id="last_name" name="last_name">
    </fieldset>
    <fieldset class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email">
    </fieldset>
    <fieldset class="mb-3">
        <label for="password" class="form-label">Mot de passe</label>
        <input type="password" class="form-control" id="password" name="password">
    </fieldset>
    <button type="submit" class="btn btn-primary">Inscription</button>
</form>