
        <ul>
            <?php
                foreach ($categories as $item) {?>
                    <li>
                        <article>
                            <h2><?= $item->getName() ?></h2>
                            <a href="index.php?route=get-category&id=<?= $item->getId() ?>">Voir la catégorie</a>
                        </article>
                    </li>
            <?php
                }
            ?>
        </ul>


