<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="username" class="form-label">
                <?= $this->translator->translate("registration_name_label") ?>
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("registration_email_label") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                <?= $this->translator->translate("registration_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
                <?= $this->translator->translate("registration_confirm_pass_label") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control"/>
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("registration_btn") ?></button>
        </fieldset>
    </form>
    <p>
        <?= $this->translator->translate("registration_question") ?> <a href="index.php"> <?= $this->translator->translate("registration_login_link") ?> </a>
    </p>
</main>