<main id="post">
    <article class="container mb-5">
        <header>
            <img class="img-fluid" src="https://picsum.photos/id/17/2000/600" alt="" />
            <h1 class='my-5'>
                Voiceover Victory: Navigating the Landscape of Screen Reader-Friendly Web Development
            </h1>
        </header>
        <section>
            <?php 
                switch ($post){
                    case 'voiceover':
                        echo checkPost($category, 3);
                        break;
        } ?></section>
    </article>

</main>